name: CI

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]

env:
  source_path: src/

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: npm ci
        working-directory: ${{ env.source_path }}

      - name: Run tests
        run: npm run lint-test
        working-directory: ${{ env.source_path }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.source_path }}
