name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release type"
        type: choice
        required: true
        default: "prerelease"
        options:
          - "prerelease"
          - "release"

env:
  source_path: src/

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fail publish
        if: github.event.inputs.version == 'release' && github.ref != 'refs/heads/main'
        run: |
          echo "Releases can only be published from the main branch"
          exit 1

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: npm ci
        working-directory: ${{ env.source_path }}

      - name: Run tests
        run: npm run lint-test
        working-directory: ${{ env.source_path }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.source_path }}

      - name: Publish prerelease
        if: github.event.inputs.version == 'prerelease'
        run: |
          npm version prerelease --preid=${{ github.run_number }} --no-git-tag-version
          npm publish --tag next
        working-directory: ${{ env.source_path }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Publish release
        if: github.event.inputs.version == 'release'
        run: npm publish --tag latest
        working-directory: ${{ env.source_path }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
